apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2025-01-02T20:38:48Z"
  generation: 4
  labels:
    app: dbserver
  name: dbserver
  namespace: storage-review
  resourceVersion: "138352521"
  uid: 8dcd159c-0a95-49f4-aab3-0d7236d27a11
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dbserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dbserver
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: world-cred
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: world-cred
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: world-cred
        image: docker.io/lmsantosopenshift/mysql-app:v1
        imagePullPolicy: IfNotPresent
        name: mysql-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbserver-lvm
        - mountPath: /home/sharedfiles
          name: shared-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dbserver-lvm
        persistentVolumeClaim:
          claimName: dbserver-lvm-pvc
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-02T20:39:05Z"
    lastUpdateTime: "2025-01-02T20:39:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-02T20:38:48Z"
    lastUpdateTime: "2025-01-02T21:17:43Z"
    message: ReplicaSet "dbserver-6569779c69" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
