apiVersion: apps/v1
kind: Deployment
metadata:
  name: long-load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: long-load
  template:
    metadata:
      labels:
        app: long-load
    spec:
      restartPolicy: Always
      containers:
      - image: docker.io/lmsantosopenshift/long-load:latest
        name: long-load
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: START_DELAY
          value: "15000" # 15 seconds delay
        ports:
        - containerPort: 3000
