apiVersion: v1
kind: Pod
metadata:
  name: long-load
spec:
  containers:
  - image: docker.io/lmsantosopenshift/long-load:latest
    name: long-load
    securityContext:
      allowPrivilegeEscalation: false
    env:
    - name: START_DELAY
      value: "60000"
  restartPolicy: Always
